modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="factoriores"
version="${file.jarVersion}"
displayName="FactoriOres"
credits="Credits go here"
authors="Seraphaestus"
description='''
Mod description goes here
'''

[[dependencies.factoriores]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.factoriores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
